spring:
  profiles:
    group:
      "devEnv": "common, dev"
---
spring:
  config:
    activate:
      on-profile: "common"
  application:
    name: dp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
cookie:
  expiration: 86400000
